import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import nextEnv from "@next/env";

nextEnv.loadEnvConfig(process.cwd());
const output = path.resolve("out");
const pages = [];
async function collect(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) await collect(filename);
    else if (entry.name.endsWith(".html")) pages.push(filename);
  }
}
await collect(output);
if (!pages.length) throw new Error("Static export has no HTML pages");

// Static export cannot use per-request nonces. Allow only built inline scripts.
const hashes = new Set();
const documents = [];
for (const filename of pages) {
  const html = await readFile(filename, "utf8");
  for (const [, attributes, script] of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    if (!/\bsrc\s*=/i.test(attributes) && script) {
      hashes.add(`'sha256-${createHash("sha256").update(script).digest("base64")}'`);
    }
  }
  documents.push([filename, html]);
}
const connections = new Set(["'self'"]);
const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL;
if (apiBase && !apiBase.startsWith("/")) {
  const url = new URL(apiBase);
  if (!["https:", "http:"].includes(url.protocol) || url.username || url.password) {
    throw new Error("API base must be an HTTP(S) URL without credentials");
  }
  connections.add(url.origin);
  url.protocol = url.protocol === "https:" ? "wss:" : "ws:";
  connections.add(url.origin);
}
const policy = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(" ")}`,
  "script-src-attr 'none'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  `connect-src ${[...connections].join(" ")}`,
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");
const escaped = policy.replaceAll("&", "&amp;").replaceAll('"', "&quot;");
for (const [filename, html] of documents) {
  const clean = html.replace(/<meta\s+data-bci-security="csp"[^>]*>/g, "");
  await writeFile(filename, clean.replace("<head>", `<head><meta data-bci-security="csp" http-equiv="Content-Security-Policy" content="${escaped}">`));
}
await writeFile(path.join(output, "security-headers.conf"),
  `# Generated by npm run build; deploy with this exact static export.\nadd_header Content-Security-Policy "${policy}; frame-ancestors 'none'" always;\n`);
console.log(`CSP generated for ${pages.length} pages with ${hashes.size} script hashes`);
